color0 #404750
color1 #ffb4ab
color2 #94ccff
color3 #afc9e4
color4 #ebb2ff
color5 #94ccff
color6 #afc9e4
color7 #e0e2e8
color8 #8a919b
color9 #ffb4ab
color10 #94ccff
color11 #afc9e4
color12 #ebb2ff
color13 #94ccff
color14 #afc9e4
color15 #e0e2e8

cursor                #e0e2e8
cursor_text_color     #101417
background            #101417
foreground            #e0e2e8
selection_foreground  #c0c7d1
selection_background  #404750
active_border_color   #94ccff
inactive_border_color #404750
url_color             #94ccff

active_tab_foreground   #003352
active_tab_background   #94ccff
inactive_tab_foreground #c0c7d1
inactive_tab_background #404750
cursor_trail_color      #c0c7d1
