color0 #44474b
color1 #ffb4ab
color2 #bbc8d5
color3 #c3c7cd
color4 #d3c1d3
color5 #bbc8d5
color6 #c3c7cd
color7 #e4e2e2
color8 #8e9195
color9 #ffb4ab
color10 #bbc8d5
color11 #c3c7cd
color12 #d3c1d3
color13 #bbc8d5
color14 #c3c7cd
color15 #e4e2e2

cursor                #e4e2e2
cursor_text_color     #131314
background            #131314
foreground            #e4e2e2
selection_foreground  #c4c7cb
selection_background  #44474b
active_border_color   #bbc8d5
inactive_border_color #44474b
url_color             #bbc8d5

active_tab_foreground   #26323c
active_tab_background   #bbc8d5
inactive_tab_foreground #c4c7cb
inactive_tab_background #44474b
cursor_trail_color      #c4c7cb
